version: "3.8"

services:
  php-auth-server:
    container_name: ${APP_NAME}-php
    build:
      context: .
      dockerfile: docker/conf/php/Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - main_network
    restart: unless-stopped
    links:
      - db

  db:
    container_name: ${APP_NAME}-mysql
    image: mysql:latest
    build:
      dockerfile: docker/conf/php/Dockerfile
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    command: mysqld --user=mysql --sql-mode=""
    volumes:
      - db:/var/lib/mysql
    networks:
      - main_network
    restart: unless-stopped

  nginx-auth-server:
    container_name: ${APP_NAME}-nginx
    build:
      dockerfile: docker/conf/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    networks:
      - main_network
    restart: unless-stopped

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - main_network

volumes:
    db:
        driver: local

networks:
  main_network:
    driver: bridge
    name: ${APP_NAME}-main-network
    ipam:
      driver: default
